site_name: OMOP Dental Dev
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.follow
  logo: img/OHDSI_black.png
  favicon: img/favicon.ico
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: True
  - attr_list
extra:
  social:
    - icon: fontawesome/brands/html5
      link: https://www.ohdsi.org/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ohdsi/posts/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gopi-kris/omop-dental-dev
nav:
  - Home: index.md
  - Getting started:
      - Learn fundamentals: learn.md
  - About: about.md